Update cafein

diff --git a/.scripts/cafein b/.scripts/cafein
--- a/.scripts/cafein
+++ b/.scripts/cafein
@@ -9,6 +9,13 @@ PROCESS_NAME="hypridle"
 # Find the Process ID (PID) of the specified process
 PID=$(pgrep -x $PROCESS_NAME)
 
+run_cmd() {
+    "$@" >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        echo "Error while running: $*"
+    fi
+}
+
 # Check if the script was run with an argument
 if [ -z "$1" ]; then
     echo "Usage: $0 [start|stop|continue|kill|toggle]"
@@ -46,13 +53,14 @@ case $1 in
         ;;
     toggle)
         if [ -z "$PID" ]; then
-            echo "hypridle activating."
-            hypridle& disown& notify-send '☕Cafein' 'Cafein disabled.'
+            echo "Hypridle activating."
+            hypridle >/dev/null 2>&1& disown >/dev/null 2>&1
+            notify-send '☕Cafein' 'Cafein disabled.'
         else
             echo "hypridle is running with PID: $PID."
             echo "Killing process '$PROCESS_NAME' (PID: $PID)..."
             kill -9 $PID # Send the KILL signal to terminate the process
-            echo "Process killed."& notify-send '☕Cafein' 'Cafein activated.'
+            echo "Hyprilde stopped."& notify-send '☕Cafein' 'Cafein activated.'
         fi
         ;;
     start)
